package ultrabitnet.accel

import spinal.core._
import spinal.lib._

import scala.language.postfixOps

case class BitNetUnifiedResidentTensorRelatedClockBridgeConfig(
    backend: BitNetUnifiedResidentTensorFastBackendConfig =
      BitNetUnifiedResidentTensorFastBackendConfig(),
    toggleSynchronizerDepth: Int = 2) {
  require(toggleSynchronizerDepth >= 2)
}

/** Small part of a read response which must be retained independently of the
  * physical RAM output.
  *
  * The 4096-bit word vector is deliberately absent.  The physical backend
  * retains packed and activation results in separate typed response slots,
  * and this bridge prevents a slot from being reused until the slow consumer
  * acknowledges the current response.
  */
case class BitNetUnifiedResidentTensorFastReadResponseMetadata(
    cfg: BitNetUnifiedResidentTensorFastBackendConfig) extends Bundle {
  private val layout = cfg.scratchpad.layout
  val absoluteRow = UInt(layout.rowAddressWidth bits)
  val bankMask = Bits(layout.bankCount bits)
  val tag = UInt(cfg.tagWidth bits)
}

/** Shared identity retained for one four-lane packed response.
  *
  * Segment data is deliberately absent: the backend owns those 4096 bits
  * until all requested lanes have been acknowledged by the slow consumer.
  */
case class BitNetUnifiedResidentTensorFastPackedReadParallelHeader(
    cfg: BitNetUnifiedResidentTensorFastBackendConfig) extends Bundle {
  private val layout = cfg.scratchpad.layout
  val absoluteRow = UInt(layout.rowAddressWidth bits)
  val tag = UInt(cfg.tagWidth bits)
  val bankMask = Bits(layout.bankCount bits)
  val laneMask = Bits(layout.packedTransportSegmentCount bits)
}

/** Zero-copy related-clock bridge for the dual-pumped resident tensor RAM.
  *
  * `slowClk` and `fastClk` must be generated by the same MMCM, with `fastClk`
  * exactly twice `slowClk`, and constrained as timing-related clocks.  Toggle
  * ownership is nevertheless synchronized explicitly; correctness never
  * assumes that reset releases the backend in F0.  A fast-side command Stream
  * simply remains valid until the backend advertises its required F0/F1 slot.
  *
  * Slow-to-fast commands use a deferred-ready mailbox.  When a slow Stream is
  * presented, its request toggle crosses immediately, but slow `ready` is not
  * asserted until the backend has accepted that command.  Consequently the
  * producer is required by the normal Stream contract to keep both `valid`
  * and the complete payload stable throughout the stall.  The wide payload is
  * sampled directly by the backend and is not copied into another 4096-bit
  * register bank in this bridge.
  *
  * Fast read returns have a response toggle plus retained row/mask/tag only.
  * The synchronized toggle captures that small metadata into a slow-domain
  * receive slot before it is exposed to downstream authentication.  Their
  * wide words remain on the corresponding backend BRAM read port.  A second
  * command of that read type is blocked until slow acknowledgement, so
  * arbitrary slow response backpressure cannot change the visible data.  A
  * write sharing that physical readWriteSync port is still allowed: the fast
  * backend's required `duringWrite = noChange` contract preserves the held
  * read output.  A replacement backend without that explicit RAM policy must
  * instead interlock same-port writes here.  The two write commits are small
  * and are retained in full.  Thus none of the four backend Flow pulses can be
  * lost even though all slow outputs are backpressured Streams.
  *
  * Both resets must be asserted for a new session, but their deassertion edges
  * may have any phase relationship.  Independently resetting only one side of
  * a live toggle transaction is intentionally outside this bridge contract.
  */
class BitNetUnifiedResidentTensorScratchpadRelatedClockBridge(
    cfg: BitNetUnifiedResidentTensorRelatedClockBridgeConfig =
      BitNetUnifiedResidentTensorRelatedClockBridgeConfig())
    extends Component {
  private val backendCfg = cfg.backend
  private val layout = backendCfg.scratchpad.layout
  private val packedReadLaneCount = layout.packedTransportSegmentCount
  private val packedReadFullLaneMask =
    (BigInt(1) << packedReadLaneCount) - 1

  val io = new Bundle {
    val slowClk = in Bool()
    val slowResetn = in Bool()
    val fastClk = in Bool()
    val fastResetn = in Bool()

    // Slow-domain clients.  Input payloads must obey Stream stability while
    // ready is low; ready means the fast backend has really accepted them.
    val packedRead = slave(Stream(
      BitNetUnifiedResidentTensorFastReadCommand(backendCfg)))
    val packedReadData = master(
      BitNetUnifiedResidentTensorFastPackedReadParallelChannel(backendCfg))
    val activationWrite = slave(Stream(
      BitNetUnifiedResidentTensorFastActivationWriteCommand(backendCfg)))
    val activationWriteCommit = master(Stream(
      BitNetUnifiedResidentTensorFastWriteCommit(backendCfg)))

    val activationRead = slave(Stream(
      BitNetUnifiedResidentTensorFastReadCommand(backendCfg)))
    val activationReadData = master(Stream(
      BitNetUnifiedResidentTensorFastActivationReadResponse(backendCfg)))
    val packedWrite = slave(Stream(
      BitNetUnifiedResidentTensorFastPackedWriteCommand(backendCfg)))
    val packedWriteCommit = master(Stream(
      BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg)))

    // Fast-domain backend attachment.  The backend is intentionally not
    // instantiated here so OOC timing and integration can place it freely.
    val backendPackedRead = master(Stream(
      BitNetUnifiedResidentTensorFastReadCommand(backendCfg)))
    val backendPackedReadData = slave(Flow(
      BitNetUnifiedResidentTensorFastPackedReadParallelPayload(backendCfg)))
    val backendActivationWrite = master(Stream(
      BitNetUnifiedResidentTensorFastActivationWriteCommand(backendCfg)))
    val backendActivationWriteCommit = slave(Flow(
      BitNetUnifiedResidentTensorFastWriteCommit(backendCfg)))

    val backendActivationRead = master(Stream(
      BitNetUnifiedResidentTensorFastReadCommand(backendCfg)))
    val backendActivationReadData = slave(Flow(
      BitNetUnifiedResidentTensorFastActivationReadResponse(backendCfg)))
    val backendPackedWrite = master(Stream(
      BitNetUnifiedResidentTensorFastPackedWriteCommand(backendCfg)))
    val backendPackedWriteCommit = slave(Flow(
      BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg)))

    val commandPending = out Bits(4 bits)
    val responsePending = out Bits(4 bits)
    val protocolFaultSticky = out Bool()
  }

  val slowCd = ClockDomain(
    clock = io.slowClk,
    reset = io.slowResetn,
    config = ClockDomainConfig(
      clockEdge = RISING,
      resetKind = ASYNC,
      resetActiveLevel = LOW))
  val fastCd = ClockDomain(
    clock = io.fastClk,
    reset = io.fastResetn,
    config = ClockDomainConfig(
      clockEdge = RISING,
      resetKind = ASYNC,
      resetActiveLevel = LOW))

  // Direct multibit crossings are ownership-held payloads.  Only their
  // toggles pass through synchronizers; the crossClockDomain tag makes that
  // deliberate constraint visible to Spinal/Vivado CDC processing.
  val packedReadRequestX = Bool()
  val packedReadCommandAckX = Bool()
  val packedReadPayloadX =
    BitNetUnifiedResidentTensorFastReadCommand(backendCfg)
  val activationWriteRequestX = Bool()
  val activationWriteCommandAckX = Bool()
  val activationWritePayloadX =
    BitNetUnifiedResidentTensorFastActivationWriteCommand(backendCfg)
  val activationReadRequestX = Bool()
  val activationReadCommandAckX = Bool()
  val activationReadPayloadX =
    BitNetUnifiedResidentTensorFastReadCommand(backendCfg)
  val packedWriteRequestX = Bool()
  val packedWriteCommandAckX = Bool()
  val packedWritePayloadX =
    BitNetUnifiedResidentTensorFastPackedWriteCommand(backendCfg)

  val packedReadResponseRequestX = Bool()
  val packedReadResponseAckX = Bool()
  val packedReadResponseHeaderX =
    BitNetUnifiedResidentTensorFastPackedReadParallelHeader(backendCfg)
  val packedReadResponseSegmentsX = Vec(
    BitNetUnifiedResidentPackedI8TokenLaneSegment(backendCfg.scratchpad),
    packedReadLaneCount)

  val activationReadResponseRequestX = Bool()
  val activationReadResponseAckX = Bool()
  val activationReadResponseMetadataX =
    BitNetUnifiedResidentTensorFastReadResponseMetadata(backendCfg)
  val activationReadResponseWordsX = Vec(
    BitNetUnifiedResidentActivationWord(backendCfg.scratchpad),
    layout.bankCount)

  val activationWriteCommitRequestX = Bool()
  val activationWriteCommitAckX = Bool()
  val activationWriteCommitPayloadX =
    BitNetUnifiedResidentTensorFastWriteCommit(backendCfg)
  val packedWriteCommitRequestX = Bool()
  val packedWriteCommitAckX = Bool()
  val packedWriteCommitPayloadX =
    BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg)

  val fastProtocolFaultX = Bool()

  Seq(
    packedReadRequestX,
    packedReadCommandAckX,
    packedReadPayloadX,
    activationWriteRequestX,
    activationWriteCommandAckX,
    activationWritePayloadX,
    activationReadRequestX,
    activationReadCommandAckX,
    activationReadPayloadX,
    packedWriteRequestX,
    packedWriteCommandAckX,
    packedWritePayloadX,
    packedReadResponseRequestX,
    packedReadResponseAckX,
    packedReadResponseHeaderX,
    packedReadResponseSegmentsX,
    activationReadResponseRequestX,
    activationReadResponseAckX,
    activationReadResponseMetadataX,
    activationReadResponseWordsX,
    activationWriteCommitRequestX,
    activationWriteCommitAckX,
    activationWriteCommitPayloadX,
    packedWriteCommitRequestX,
    packedWriteCommitAckX,
    packedWriteCommitPayloadX,
    fastProtocolFaultX
  ).foreach(_.addTag(crossClockDomain))

  val slowArea = new ClockingArea(slowCd) {
    // -------------------------------------------------------------------
    // Four independent deferred-ready command mailboxes.
    // -------------------------------------------------------------------
    val packedReadRequest = RegInit(False)
    val packedReadIssued = RegInit(False)
    val packedReadAckSync = BufferCC(
      packedReadCommandAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    io.packedRead.ready :=
      packedReadIssued && packedReadAckSync === packedReadRequest
    when(!packedReadIssued && io.packedRead.valid) {
      packedReadRequest := !packedReadRequest
      packedReadIssued := True
    }
    when(io.packedRead.fire) {
      packedReadIssued := False
    }
    packedReadRequestX := packedReadRequest
    packedReadPayloadX := io.packedRead.payload

    val activationWriteRequest = RegInit(False)
    val activationWriteIssued = RegInit(False)
    val activationWriteAckSync = BufferCC(
      activationWriteCommandAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    io.activationWrite.ready :=
      activationWriteIssued &&
        activationWriteAckSync === activationWriteRequest
    when(!activationWriteIssued && io.activationWrite.valid) {
      activationWriteRequest := !activationWriteRequest
      activationWriteIssued := True
    }
    when(io.activationWrite.fire) {
      activationWriteIssued := False
    }
    activationWriteRequestX := activationWriteRequest
    activationWritePayloadX := io.activationWrite.payload

    val activationReadRequest = RegInit(False)
    val activationReadIssued = RegInit(False)
    val activationReadAckSync = BufferCC(
      activationReadCommandAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    io.activationRead.ready :=
      activationReadIssued && activationReadAckSync === activationReadRequest
    when(!activationReadIssued && io.activationRead.valid) {
      activationReadRequest := !activationReadRequest
      activationReadIssued := True
    }
    when(io.activationRead.fire) {
      activationReadIssued := False
    }
    activationReadRequestX := activationReadRequest
    activationReadPayloadX := io.activationRead.payload

    val packedWriteRequest = RegInit(False)
    val packedWriteIssued = RegInit(False)
    val packedWriteAckSync = BufferCC(
      packedWriteCommandAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    io.packedWrite.ready :=
      packedWriteIssued && packedWriteAckSync === packedWriteRequest
    when(!packedWriteIssued && io.packedWrite.valid) {
      packedWriteRequest := !packedWriteRequest
      packedWriteIssued := True
    }
    when(io.packedWrite.fire) {
      packedWriteIssued := False
    }
    packedWriteRequestX := packedWriteRequest
    packedWritePayloadX := io.packedWrite.payload

    // -------------------------------------------------------------------
    // Four fast-to-slow retained response mailboxes.  The packed-read mailbox
    // retains one shared header and a four-bit pending mask; its four wide
    // token-lane segments remain ownership-held direct crossings.
    // -------------------------------------------------------------------
    val packedReadResponseRequestSync = BufferCC(
      packedReadResponseRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val packedReadResponseAck = RegInit(False)
    val packedReadResponseSegmentPending =
      Reg(Bits(packedReadLaneCount bits)) init 0
    val packedReadResponseSlowHeader = Reg(
      BitNetUnifiedResidentTensorFastPackedReadParallelHeader(
        backendCfg)) init (
      BitNetUnifiedResidentTensorFastPackedReadParallelHeader(
        backendCfg).getZero)
    val packedReadResponseAvailable =
      packedReadResponseRequestSync =/= packedReadResponseAck
    when(!packedReadResponseSegmentPending.orR &&
      packedReadResponseAvailable) {
      packedReadResponseSlowHeader := packedReadResponseHeaderX
      packedReadResponseSegmentPending := packedReadResponseHeaderX.laneMask
    }
    io.packedReadData.absoluteRow :=
      packedReadResponseSlowHeader.absoluteRow
    io.packedReadData.tag := packedReadResponseSlowHeader.tag
    io.packedReadData.bankMask := packedReadResponseSlowHeader.bankMask
    io.packedReadData.laneMask := packedReadResponseSlowHeader.laneMask
    io.packedReadData.segmentValid := packedReadResponseSegmentPending
    for (lane <- 0 until packedReadLaneCount) {
      io.packedReadData.segments(lane) :=
        packedReadResponseSegmentsX(lane)
    }
    val packedReadResponseFireMask =
      packedReadResponseSegmentPending & io.packedReadData.segmentReady
    val packedReadResponsePendingAfter =
      packedReadResponseSegmentPending & ~packedReadResponseFireMask
    when(packedReadResponseSegmentPending.orR) {
      packedReadResponseSegmentPending := packedReadResponsePendingAfter
      when(!packedReadResponsePendingAfter.orR) {
        packedReadResponseAck := packedReadResponseRequestSync
      }
    }
    packedReadResponseAckX := packedReadResponseAck

    val activationReadResponseRequestSync = BufferCC(
      activationReadResponseRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val activationReadResponseAck = RegInit(False)
    val activationReadResponseCaptured = RegInit(False)
    val activationReadResponseSlowMetadata = Reg(
      BitNetUnifiedResidentTensorFastReadResponseMetadata(backendCfg)) init (
      BitNetUnifiedResidentTensorFastReadResponseMetadata(
        backendCfg).getZero)
    val activationReadResponseAvailable =
      activationReadResponseRequestSync =/= activationReadResponseAck
    when(!activationReadResponseCaptured && activationReadResponseAvailable) {
      activationReadResponseSlowMetadata := activationReadResponseMetadataX
      activationReadResponseCaptured := True
    }
    io.activationReadData.valid := activationReadResponseCaptured
    io.activationReadData.absoluteRow :=
      activationReadResponseSlowMetadata.absoluteRow
    io.activationReadData.bankMask := activationReadResponseSlowMetadata.bankMask
    io.activationReadData.tag := activationReadResponseSlowMetadata.tag
    for (bank <- 0 until layout.bankCount) {
      io.activationReadData.words(bank) := activationReadResponseWordsX(bank)
    }
    when(io.activationReadData.fire) {
      activationReadResponseCaptured := False
      activationReadResponseAck := activationReadResponseRequestSync
    }
    activationReadResponseAckX := activationReadResponseAck

    val activationWriteCommitRequestSync = BufferCC(
      activationWriteCommitRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val activationWriteCommitAck = RegInit(False)
    // The fast owner holds its commit payload until this acknowledgement.
    // Capture that small payload once in the slow domain before exposing it to
    // semantic authentication.  Besides being the conventional bundled-data
    // mailbox receive stage, this prevents a commit mismatch from travelling
    // combinationally through fail-stop/ready logic to an unrelated client.
    val activationWriteCommitCaptured = RegInit(False)
    val activationWriteCommitSlowPayload = Reg(
      BitNetUnifiedResidentTensorFastWriteCommit(backendCfg)) init (
      BitNetUnifiedResidentTensorFastWriteCommit(backendCfg).getZero)
    val activationWriteCommitAvailable =
      activationWriteCommitRequestSync =/= activationWriteCommitAck
    when(!activationWriteCommitCaptured && activationWriteCommitAvailable) {
      activationWriteCommitSlowPayload := activationWriteCommitPayloadX
      activationWriteCommitCaptured := True
    }
    io.activationWriteCommit.valid := activationWriteCommitCaptured
    io.activationWriteCommit.payload := activationWriteCommitSlowPayload
    when(io.activationWriteCommit.fire) {
      activationWriteCommitCaptured := False
      activationWriteCommitAck := activationWriteCommitRequestSync
    }
    activationWriteCommitAckX := activationWriteCommitAck

    val packedWriteCommitRequestSync = BufferCC(
      packedWriteCommitRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val packedWriteCommitAck = RegInit(False)
    val packedWriteCommitCaptured = RegInit(False)
    val packedWriteCommitSlowPayload = Reg(
      BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg)) init (
      BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg).getZero)
    val packedWriteCommitAvailable =
      packedWriteCommitRequestSync =/= packedWriteCommitAck
    when(!packedWriteCommitCaptured && packedWriteCommitAvailable) {
      packedWriteCommitSlowPayload := packedWriteCommitPayloadX
      packedWriteCommitCaptured := True
    }
    io.packedWriteCommit.valid := packedWriteCommitCaptured
    io.packedWriteCommit.payload := packedWriteCommitSlowPayload
    when(io.packedWriteCommit.fire) {
      packedWriteCommitCaptured := False
      packedWriteCommitAck := packedWriteCommitRequestSync
    }
    packedWriteCommitAckX := packedWriteCommitAck

    io.commandPending := packedWriteIssued ## activationReadIssued ##
      activationWriteIssued ## packedReadIssued
    io.responsePending := io.packedWriteCommit.valid ##
      io.activationReadData.valid ## io.activationWriteCommit.valid ##
      io.packedReadData.segmentValid.orR
    io.protocolFaultSticky := BufferCC(
      fastProtocolFaultX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
  }

  val fastArea = new ClockingArea(fastCd) {
    // -------------------------------------------------------------------
    // Backend command side.  Per-type busy extends from backend acceptance
    // through slow response acknowledgement, which keeps a BRAM read port's
    // wide result stable without a second wide register bank.  Same-port
    // writes remain legal because the backend RAM contract is noChange.
    // -------------------------------------------------------------------
    val packedReadRequestSync = BufferCC(
      packedReadRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val packedReadCommandAck = RegInit(False)
    val packedReadBusy = RegInit(False)
    io.backendPackedRead.valid :=
      packedReadRequestSync =/= packedReadCommandAck && !packedReadBusy
    io.backendPackedRead.payload := packedReadPayloadX
    when(io.backendPackedRead.fire) {
      packedReadCommandAck := packedReadRequestSync
      packedReadBusy := True
    }
    packedReadCommandAckX := packedReadCommandAck

    val activationWriteRequestSync = BufferCC(
      activationWriteRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val activationWriteCommandAck = RegInit(False)
    val activationWriteBusy = RegInit(False)
    io.backendActivationWrite.valid :=
      activationWriteRequestSync =/= activationWriteCommandAck &&
        !activationWriteBusy
    io.backendActivationWrite.payload := activationWritePayloadX
    when(io.backendActivationWrite.fire) {
      activationWriteCommandAck := activationWriteRequestSync
      activationWriteBusy := True
    }
    activationWriteCommandAckX := activationWriteCommandAck

    val activationReadRequestSync = BufferCC(
      activationReadRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val activationReadCommandAck = RegInit(False)
    val activationReadBusy = RegInit(False)
    io.backendActivationRead.valid :=
      activationReadRequestSync =/= activationReadCommandAck &&
        !activationReadBusy
    io.backendActivationRead.payload := activationReadPayloadX
    when(io.backendActivationRead.fire) {
      activationReadCommandAck := activationReadRequestSync
      activationReadBusy := True
    }
    activationReadCommandAckX := activationReadCommandAck

    val packedWriteRequestSync = BufferCC(
      packedWriteRequestX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val packedWriteCommandAck = RegInit(False)
    val packedWriteBusy = RegInit(False)
    io.backendPackedWrite.valid :=
      packedWriteRequestSync =/= packedWriteCommandAck && !packedWriteBusy
    io.backendPackedWrite.payload := packedWritePayloadX
    when(io.backendPackedWrite.fire) {
      packedWriteCommandAck := packedWriteRequestSync
      packedWriteBusy := True
    }
    packedWriteCommandAckX := packedWriteCommandAck

    // -------------------------------------------------------------------
    // Read response ownership.  Only one shared packed header is copied.
    // Token-lane segments are direct, stable crossings from the backend's
    // retained packed response row.
    // -------------------------------------------------------------------
    val packedReadResponseAckSync = BufferCC(
      packedReadResponseAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val packedReadResponseRequest = RegInit(False)
    val packedReadResponseAwaitingAck = RegInit(False)
    val packedReadResponseHeader = Reg(
      BitNetUnifiedResidentTensorFastPackedReadParallelHeader(
        backendCfg)) init (
      BitNetUnifiedResidentTensorFastPackedReadParallelHeader(
        backendCfg).getZero)
    val packedReadResponseEmpty =
      packedReadResponseRequest === packedReadResponseAckSync
    val packedReadResponseExpected =
      packedReadBusy || io.backendPackedRead.fire
    val packedReadResponseLaneMaskLegal =
      io.backendPackedReadData.laneMask === B(
        packedReadFullLaneMask, packedReadLaneCount bits)
    val packedReadResponseCanCapture =
      packedReadResponseExpected && !packedReadResponseAwaitingAck &&
        packedReadResponseEmpty && packedReadResponseLaneMaskLegal
    when(io.backendPackedReadData.valid) {
      when(packedReadResponseCanCapture) {
        packedReadResponseHeader.absoluteRow :=
          io.backendPackedReadData.absoluteRow
        packedReadResponseHeader.tag := io.backendPackedReadData.tag
        packedReadResponseHeader.bankMask := io.backendPackedReadData.bankMask
        packedReadResponseHeader.laneMask := io.backendPackedReadData.laneMask
        packedReadResponseRequest := !packedReadResponseRequest
        packedReadResponseAwaitingAck := True
      }
    }
    when(packedReadResponseAwaitingAck && packedReadResponseEmpty) {
      packedReadResponseAwaitingAck := False
      packedReadBusy := False
    }
    packedReadResponseRequestX := packedReadResponseRequest
    packedReadResponseHeaderX := packedReadResponseHeader
    for (lane <- 0 until packedReadLaneCount) {
      packedReadResponseSegmentsX(lane) :=
        io.backendPackedReadData.segments(lane)
    }

    val activationReadResponseAckSync = BufferCC(
      activationReadResponseAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val activationReadResponseRequest = RegInit(False)
    val activationReadResponseAwaitingAck = RegInit(False)
    val activationReadResponseMetadata = Reg(
      BitNetUnifiedResidentTensorFastReadResponseMetadata(backendCfg)) init (
      BitNetUnifiedResidentTensorFastReadResponseMetadata(
        backendCfg).getZero)
    val activationReadResponseEmpty =
      activationReadResponseRequest === activationReadResponseAckSync
    val activationReadResponseExpected =
      activationReadBusy || io.backendActivationRead.fire
    when(io.backendActivationReadData.valid) {
      when(activationReadResponseExpected &&
        !activationReadResponseAwaitingAck &&
        activationReadResponseEmpty) {
        activationReadResponseMetadata.absoluteRow :=
          io.backendActivationReadData.absoluteRow
        activationReadResponseMetadata.bankMask :=
          io.backendActivationReadData.bankMask
        activationReadResponseMetadata.tag :=
          io.backendActivationReadData.tag
        activationReadResponseRequest := !activationReadResponseRequest
        activationReadResponseAwaitingAck := True
      }
    }
    when(activationReadResponseAwaitingAck &&
      activationReadResponseEmpty) {
      activationReadResponseAwaitingAck := False
      activationReadBusy := False
    }
    activationReadResponseRequestX := activationReadResponseRequest
    activationReadResponseMetadataX := activationReadResponseMetadata
    for (bank <- 0 until layout.bankCount) {
      activationReadResponseWordsX(bank) :=
        io.backendActivationReadData.words(bank)
    }

    // -------------------------------------------------------------------
    // Write commits are small enough to retain in full.  This converts the
    // backend's one-cycle Flow pulses into lossless slow-domain Streams.
    // -------------------------------------------------------------------
    val activationWriteCommitAckSync = BufferCC(
      activationWriteCommitAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val activationWriteCommitRequest = RegInit(False)
    val activationWriteCommitAwaitingAck = RegInit(False)
    val activationWriteCommitPayload = Reg(
      BitNetUnifiedResidentTensorFastWriteCommit(backendCfg)) init (
      BitNetUnifiedResidentTensorFastWriteCommit(backendCfg).getZero)
    val activationWriteCommitEmpty =
      activationWriteCommitRequest === activationWriteCommitAckSync
    val activationWriteCommitExpected =
      activationWriteBusy || io.backendActivationWrite.fire
    when(io.backendActivationWriteCommit.valid) {
      when(activationWriteCommitExpected &&
        !activationWriteCommitAwaitingAck && activationWriteCommitEmpty) {
        activationWriteCommitPayload :=
          io.backendActivationWriteCommit.payload
        activationWriteCommitRequest := !activationWriteCommitRequest
        activationWriteCommitAwaitingAck := True
      }
    }
    when(activationWriteCommitAwaitingAck &&
      activationWriteCommitEmpty) {
      activationWriteCommitAwaitingAck := False
      activationWriteBusy := False
    }
    activationWriteCommitRequestX := activationWriteCommitRequest
    activationWriteCommitPayloadX := activationWriteCommitPayload

    val packedWriteCommitAckSync = BufferCC(
      packedWriteCommitAckX,
      init = False,
      bufferDepth = Some(cfg.toggleSynchronizerDepth),
      inputAttributes = Seq(crossClockDomain))
    val packedWriteCommitRequest = RegInit(False)
    val packedWriteCommitAwaitingAck = RegInit(False)
    val packedWriteCommitPayload = Reg(
      BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg)) init (
      BitNetUnifiedResidentTensorFastPackedWriteCommit(backendCfg).getZero)
    val packedWriteCommitEmpty =
      packedWriteCommitRequest === packedWriteCommitAckSync
    val packedWriteCommitExpected =
      packedWriteBusy || io.backendPackedWrite.fire
    when(io.backendPackedWriteCommit.valid) {
      when(packedWriteCommitExpected &&
        !packedWriteCommitAwaitingAck && packedWriteCommitEmpty) {
        packedWriteCommitPayload := io.backendPackedWriteCommit.payload
        packedWriteCommitRequest := !packedWriteCommitRequest
        packedWriteCommitAwaitingAck := True
      }
    }
    when(packedWriteCommitAwaitingAck && packedWriteCommitEmpty) {
      packedWriteCommitAwaitingAck := False
      packedWriteBusy := False
    }
    packedWriteCommitRequestX := packedWriteCommitRequest
    packedWriteCommitPayloadX := packedWriteCommitPayload

    val protocolFault = RegInit(False)
    when(io.backendPackedReadData.valid &&
      !packedReadResponseCanCapture) {
      protocolFault := True
    }
    when(io.backendActivationReadData.valid &&
      !(activationReadResponseExpected &&
        !activationReadResponseAwaitingAck &&
        activationReadResponseEmpty)) {
      protocolFault := True
    }
    when(io.backendActivationWriteCommit.valid &&
      !(activationWriteCommitExpected &&
        !activationWriteCommitAwaitingAck &&
        activationWriteCommitEmpty)) {
      protocolFault := True
    }
    when(io.backendPackedWriteCommit.valid &&
      !(packedWriteCommitExpected &&
        !packedWriteCommitAwaitingAck && packedWriteCommitEmpty)) {
      protocolFault := True
    }
    fastProtocolFaultX := protocolFault
  }
}

object GenerateBitNetUnifiedResidentTensorScratchpadRelatedClockBridge
    extends App {
  val target = args.headOption.getOrElse(
    "target/generated-bitnet-unified-resident-tensor-related-clock-bridge")
  SpinalConfig(
    mode = Verilog,
    targetDirectory = target,
    oneFilePerComponent = false
  ).generate(
    new BitNetUnifiedResidentTensorScratchpadRelatedClockBridge())
}
