#ifndef BITNET_PLDDR_DUAL_H
#define BITNET_PLDDR_DUAL_H

#include <stdint.h>

#include "compat/xparameters.h"

/*
 * Address map generated by Vivado assign_bd_address for pl_ddr4_0.
 * The aperture is 1 GiB and is independent of the PS DDR window.
 */
#define BITNET_PLDDR_BASE          UINT64_C(0x400000000)
#define BITNET_PLDDR_SIZE          UINT64_C(0x40000000)
#define BITNET_PLDDR_END           UINT64_C(0x43fffffff)
#define BITNET_PLDDR_LANE0_OFFSET  UINT64_C(0x00000000)
#define BITNET_PLDDR_LANE1_OFFSET  UINT64_C(0x10000000)
#define BITNET_PLDDR_SCRATCH_OFFSET UINT64_C(0x20000000)

#define BITNET_PLDDR_LANE_BYTES    UINT64_C(0x10000000)
#define BITNET_PLDDR_LANE0_ADDR    (BITNET_PLDDR_BASE + BITNET_PLDDR_LANE0_OFFSET)
#define BITNET_PLDDR_LANE1_ADDR    (BITNET_PLDDR_BASE + BITNET_PLDDR_LANE1_OFFSET)

#define BITNET_PSDDR_CACHE_BASE    XPAR_PS_DDR_CACHE_BASEADDR
#define BITNET_PSDDR_CACHE_SIZE    XPAR_PS_DDR_CACHE_SIZE
#define BITNET_PSDDR_CACHE_END     XPAR_PS_DDR_CACHE_HIGHADDR

#define BITNET_DUAL_DMA0_BASE      UINT32_C(0x80000000)
#define BITNET_DUAL_DMA1_BASE      UINT32_C(0x80010000)

/* One lane packet contains the common K/activation fields and only that
 * lane's output-channel groups.  Lane 0 and lane 1 are submitted concurrently
 * and the result DMA receives lane0 outputs followed by lane1 outputs. */
typedef struct {
    uint32_t magic;
    uint32_t n_lane;
    uint32_t k;
    uint32_t flags;
    uint32_t reserved[12];
} BitnetDualLanePacketHeader;

#define BITNET_DUAL_PACKET_MAGIC UINT32_C(0x42544e31) /* "BTN1" */
typedef char BitnetDualLanePacketHeaderMustBe64Bytes[
    (sizeof(BitnetDualLanePacketHeader) == 64u) ? 1 : -1];

#endif
